export const REGISTRY_V1_REVISION = '2026-09-09' as const;

export const REGISTRY_V1_ARTIFACT_PROVENANCE = 'file_00000000642c8230aa48b4825b7fbe0d@1 | KNOWLEDGE REGISTRY V1 FINAL – SCHEMA-NORMALISERAD' as const;

export type HelpbotAnswerPolicy = 'ALLOWED' | 'ALLOWED_WITH_LIMITS' | 'DENIED';
export type HelpbotRegistryStatus = 'ACTIVE' | 'ACTIVE_DENIAL_RULE' | 'SUPERSEDED';

export type HelpbotRegistryItem = Readonly<{
  knowledgeId: string;
  topicModule: string;
  sourceOwner: string;
  sourcePrecedence: string;
  authorityReference: string;
  sourceReference: string;
  validFrom: string;
  validTo: string;
  status: HelpbotRegistryStatus;
  supersedes: string;
  supersededBy: string;
  audienceRole: string;
  answerPolicy: HelpbotAnswerPolicy;
  requiredContext: string;
  canonicalFact: string;
  canonicalHelpText: string;
  prohibitedClaims: string;
}>;


// The locked final artifact carries concrete source references inside its final authority/reference column.
// V1 duplicates that verbatim value into sourceReference rather than inferring or rewriting a second source narrative.

export const KNOWLEDGE_REGISTRY_V1 = [
  {
    knowledgeId: "KR-GUIDE-001",
    topicModule: "Operativ routing / “vad gör jag nu?”",
    sourceOwner: "INCHECKAD PLATFORM",
    sourcePrecedence: "P2_LATER_MASTER_DECISION",
    authorityReference: "MASTER:2026-09-09:INTERN-HJALP-AI-LAST-PRODUCT-ARKITEKTURBESLUT",
    sourceReference: "MASTER:2026-09-09:INTERN-HJALP-AI-LAST-PRODUCT-ARKITEKTURBESLUT",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED_WITH_LIMITS",
    requiredContext: "process_type OR equivalent minimum routing context",
    canonicalFact: "En vag fordonsuppgift etablerar inte automatiskt vilken modul som äger nästa steg.",
    canonicalHelpText: "“Är detta en ny inkommande bil/Garage–Nybil-process eller en återlämnad bil som ska Check-in?”",
    prohibitedClaims: "Gissa modul, process eller ownership när minsta routingkontext saknas.",
  },
  {
    knowledgeId: "KR-PLAN-001",
    topicModule: "PLANERING → GARAGE IN",
    sourceOwner: "PLANERING",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "SOURCE:file_0000000007a081f4af119bfcc933b637:report=H-AGARUTREDNING:date=2026-09-06:production_main=4052cdc95c6fee0649479fef61d16f72e8fad65b",
    sourceReference: "SOURCE:file_0000000007a081f4af119bfcc933b637:report=H-AGARUTREDNING:date=2026-09-06:production_main=4052cdc95c6fee0649479fef61d16f72e8fad65b",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "`ordered_count/BESTÄLLT` är ett planerings-/kvantitetsbeslut. Planering KLAR materialiserar individuella Garage IN-objekt; detta bevisar inte individuell extern fordonsorder.",
    canonicalHelpText: "“Planering har beslutat hur många som ska anskaffas. När perioden släpps skapas individuella Garage-objekt.”",
    prohibitedClaims: "“BESTÄLLT betyder att just den bilen är beställd hos leverantören.”",
  },
  {
    knowledgeId: "KR-GAR-001",
    topicModule: "GARAGE IN – processidentitet",
    sourceOwner: "GARAGE",
    sourcePrecedence: "P1_CURRENT_PRODUCTION + P2_LATER_MASTER_DECISION",
    authorityReference: "`MASTER:2026-09-09:KNOWLEDGE-REGISTRY-GARAGE-ID` + `SOURCE:file_0000000007a081f4af119bfcc933b637:section=CURRENT-PROCESSKEDJA`",
    sourceReference: "`MASTER:2026-09-09:KNOWLEDGE-REGISTRY-GARAGE-ID` + `SOURCE:file_0000000007a081f4af119bfcc933b637:section=CURRENT-PROCESSKEDJA`",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "`garage_item_id` är exakt Garage-processidentitet. Ett legitimt Garage IN kan sakna reg.nr.",
    canonicalHelpText: "“Nej, bilen behöver inte ha reg.nr ännu. Garage-posten är fortfarande giltig.”",
    prohibitedClaims: "Reg.nr krävs för legitim Garage-post; reg.nr är universal processidentitet; skapa nytt Garage-object för att få identitet.",
  },
  {
    knowledgeId: "KR-NYB-001",
    topicModule: "GARAGE → NYBIL",
    sourceOwner: "GARAGE / NYBIL handoff",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "`SOURCE:file_0000000007a081f4af119bfcc933b637:section=GARAGE-NYBIL:production_main=4052cdc95c6fee0649479fef61d16f72e8fad65b` + `PR:432:merge=be3fddf5f28b7ec6a738c7e6388eee08c29e12d2`",
    sourceReference: "`SOURCE:file_0000000007a081f4af119bfcc933b637:section=GARAGE-NYBIL:production_main=4052cdc95c6fee0649479fef61d16f72e8fad65b` + `PR:432:merge=be3fddf5f28b7ec6a738c7e6388eee08c29e12d2`",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "Nybil använder exakt Garage-källa. Garage-snapshot bevaras och Nybil etablerar en separat verifierad mottagningsbild.",
    canonicalHelpText: "“Öppna Ny Bil från rätt Garage-post. Det du verifierar i Nybil skriver inte om Garage-historiken.”",
    prohibitedClaims: "Kopiera manuellt som ny källa; använda reg.nr som handoff-identitet; hävda att Nybil skriver om Garage.",
  },
  {
    knowledgeId: "KR-CHECK-001",
    topicModule: "CHECK-IN",
    sourceOwner: "CHECK-IN",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "SOURCE:file_000000009698820ab261f4af1b144e35:report=STATUS-CURRENT-FACTS:date=2026-09-06:production_main=42415491b2180b0604172bcb5cf3e91c60e0be1a",
    sourceReference: "SOURCE:file_000000009698820ab261f4af1b144e35:report=STATUS-CURRENT-FACTS:date=2026-09-06:production_main=42415491b2180b0604172bcb5cf3e91c60e0be1a",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "Check-in äger verifierad kontrollobservation. Completed Check-in innebär inte automatiskt AVAILABLE. Explicit ej uthyrningsbar + anledning kan etablera DOWNTIME.",
    canonicalHelpText: "“Check-in dokumenterar kontrollen. Klar kontroll betyder inte automatiskt att bilen är uthyrningsbar.”",
    prohibitedClaims: "`completed = AVAILABLE`; Check-in startar/avslutar RENTAL.",
  },
  {
    knowledgeId: "KR-STATUS-001",
    topicModule: "STATUS – mätare/plats current fact",
    sourceOwner: "STATUS / underlying observation owners",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "`PR:572:merge=164bd617c8b8eac232b02f71ffd7ba236b5d0b6c` + `PR:573:merge=42415491b2180b0604172bcb5cf3e91c60e0be1a` + `DEPLOYMENT:dpl_86T6ekH2tUNFMVBuEm3NBtFYQoXH`",
    sourceReference: "`PR:572:merge=164bd617c8b8eac232b02f71ffd7ba236b5d0b6c` + `PR:573:merge=42415491b2180b0604172bcb5cf3e91c60e0be1a` + `DEPLOYMENT:dpl_86T6ekH2tUNFMVBuEm3NBtFYQoXH`",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "För mätarställning och fysisk plats gäller senaste legitima verifierade observation i observationstid. Tidigare source-record skrivs inte om.",
    canonicalHelpText: "“Den senaste verifierade observationen i tid är aktuell uppgift; den äldre observationen ligger kvar.”",
    prohibitedClaims: "Senast tekniskt uppdaterade modul vinner; Status äger all fordonsstatus; Status-korrigering skapar Check-in/Rental.",
  },
  {
    knowledgeId: "KR-STATUS-002",
    topicModule: "Saludatum i STATUS",
    sourceOwner: "SALU for later change / NYBIL baseline",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "`PR:571:merge=fb5bab5cabbdd7932ae9b4f082edb4149df4cc59` + `SOURCE:file_000000009698820ab261f4af1b144e35:section=SALUDATUM`",
    sourceReference: "`PR:571:merge=fb5bab5cabbdd7932ae9b4f082edb4149df4cc59` + `SOURCE:file_000000009698820ab261f4af1b144e35:section=SALUDATUM`",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "NYBIL etablerar Saludatum-baseline. SALU äger senare verifierad ändring/current fact. Status läser men ändrar inte.",
    canonicalHelpText: "“Du kan se aktuellt Saludatum i Status, men du ändrar det inte där.”",
    prohibitedClaims: "Ändra Saludatum i Status.",
  },
  {
    knowledgeId: "KR-SALU-001",
    topicModule: "SALU → GARAGE UT",
    sourceOwner: "SALU",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "`PR:601:merge=35a8d013d9e6055361bbac5a2765a522c1e3175a` + `MIGRATION:20260908190047:lock_verified_salu_garage_recipient_void_v1` + `DEPLOYMENT:dpl_3SSWbGZrR8uN3JG1cxHspbbPkfDX`",
    sourceReference: "`PR:601:merge=35a8d013d9e6055361bbac5a2765a522c1e3175a` + `MIGRATION:20260908190047:lock_verified_salu_garage_recipient_void_v1` + `DEPLOYMENT:dpl_3SSWbGZrR8uN3JG1cxHspbbPkfDX`",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "Canonical väg är `SALU STÄNGD + SÄLJAS → exakt Garage UT`. AVVECKLA startar separat.",
    canonicalHelpText: "“När SALU avslutas korrekt med SÄLJAS skapas Garage UT. Bilen är inte terminalt UT ännu.”",
    prohibitedClaims: "SÄLJAS = SÅLD = UT; SALU avslutar Layer 1; AVVECKLA startas automatiskt.",
  },
  {
    knowledgeId: "KR-AVV-001",
    topicModule: "GARAGE UT → START AVVECKLA",
    sourceOwner: "AVVECKLA",
    sourcePrecedence: "P1_CURRENT_PRODUCTION + P2_LATER_MASTER_DECISION",
    authorityReference: "`PR:604:head=c357fe82e40824c7db4c2ac68dabb81f82eccb13:merge=a3f70a74e7922d3dd36524f93f58d5af474c5d88` + `DEPLOYMENT:dpl_9gEtbjmDscKWnfn3mFCFToSGCEPA` + `MASTER:2026-09-09:604-PRODUCTION-ACCEPTED`",
    sourceReference: "`PR:604:head=c357fe82e40824c7db4c2ac68dabb81f82eccb13:merge=a3f70a74e7922d3dd36524f93f58d5af474c5d88` + `DEPLOYMENT:dpl_9gEtbjmDscKWnfn3mFCFToSGCEPA` + `MASTER:2026-09-09:604-PRODUCTION-ACCEPTED`",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "#604 styr startgränsen. Canonical AVVECKLA-start kräver legitim Garage UT-source och exakt en öppen Layer-1-period. Efter start ligger ansvaret i AVVECKLA och generic Garage mutation/void är spärrad.",
    canonicalHelpText: "“Start AVVECKLA flyttar ansvaret till AVVECKLA. Det betyder ännu inte att bilen är UT.”",
    prohibitedClaims: "Terminal readiness krävs före start; Garage får ändras fritt efter start; direkt service-role DML är canonical väg.",
  },
  {
    knowledgeId: "KR-AVV-002",
    topicModule: "AVVECKLA → TERMINALT UT",
    sourceOwner: "AVVECKLA",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "`SOURCE:file_0000000008e08210aeba4dcf3d5f7bd1:section=AVVECKLA` + `FUNCTION:assert_garage_avveckla_ready_for_completion` + `MASTER:2026-09-09:604-START-VS-COMPLETION`",
    sourceReference: "`SOURCE:file_0000000008e08210aeba4dcf3d5f7bd1:section=AVVECKLA` + `FUNCTION:assert_garage_avveckla_ready_for_completion` + `MASTER:2026-09-09:604-START-VS-COMPLETION`",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED",
    requiredContext: "NONE",
    canonicalFact: "START AVVECKLA och TERMINALT UT är olika ansvarspunkter. Terminal completion går genom den separata canonical readiness/completion-kedjan.",
    canonicalHelpText: "“AVVECKLA är startad men bilen är inte UT ännu. Terminalt UT sker först när completion-villkoren är verifierade.”",
    prohibitedClaims: "Garage UT = UT; AVVECKLA startad = completed; readiness-gaten definierar start.",
  },
  {
    knowledgeId: "KR-INH-001",
    topicModule: "INHYRD",
    sourceOwner: "INHYRD / Vehicle Journey",
    sourcePrecedence: "P3_CURRENT_MAIN_CONTRACT",
    authorityReference: "SOURCE:file_000000002ffc820ab44b9e4e243b7742:date=2026-09-06:main=bdbaeb87ca325d5df6a8f3d2b9c6afcbc71bf953",
    sourceReference: "SOURCE:file_000000002ffc820ab44b9e4e243b7742:date=2026-09-06:main=bdbaeb87ca325d5df6a8f3d2b9c6afcbc71bf953",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED_WITH_LIMITS",
    requiredContext: "intag OR retur",
    canonicalFact: "INHYRD har separat intake- och return-väg och ska inte automatiskt behandlas som ordinarie Garage→AVVECKLA.",
    canonicalHelpText: "“Är detta intag eller retur av den inhyrda bilen?”",
    prohibitedClaims: "Hitta på fler canonical states, ekonomi- eller terminalregler än publicerad källa stödjer.",
  },
  {
    knowledgeId: "KR-ORDER-001",
    topicModule: "Individuell beställning/leverans – publicerbar gräns",
    sourceOwner: "PLANERING + currently unresolved individual owner",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "SOURCE:file_0000000007a081f4af119bfcc933b637:report=H-AGARUTREDNING:date=2026-09-06:production_main=4052cdc95c6fee0649479fef61d16f72e8fad65b",
    sourceReference: "SOURCE:file_0000000007a081f4af119bfcc933b637:report=H-AGARUTREDNING:date=2026-09-06:production_main=4052cdc95c6fee0649479fef61d16f72e8fad65b",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "ALLOWED_WITH_LIMITS",
    requiredContext: "NONE",
    canonicalFact: "Production bevisar Planering BESTÄLLT och den senare Garage/Nybil-kedjan men inte en sammanhängande verifierad individuell beställnings-/leveransmotor.",
    canonicalHelpText: "“Jag kan förklara vad BESTÄLLT betyder i Planering, men INCHECKAD har ännu ingen publicerad verifierad individuell order-/transportprocess som jag får beskriva som canonical.”",
    prohibitedClaims: "Påstå att `calloff_at` är ett verifierat leverantörsavrop; tillskriva `supplier`, `order_reference` eller confirmation-state en ej beslutad semantik.",
  },
  {
    knowledgeId: "KR-ORDER-002",
    topicModule: "Påhittad individuell order-/transport-state-machine",
    sourceOwner: "NONE – no canonical owner established",
    sourcePrecedence: "P1_CURRENT_PRODUCTION",
    authorityReference: "SOURCE:file_0000000007a081f4af119bfcc933b637:section=DET-SOM-INTE-KAN-BEVISAS",
    sourceReference: "SOURCE:file_0000000007a081f4af119bfcc933b637:section=DET-SOM-INTE-KAN-BEVISAS",
    validFrom: "2026-09-09",
    validTo: "OPEN",
    status: "ACTIVE_DENIAL_RULE",
    supersedes: "NONE",
    supersededBy: "NONE",
    audienceRole: "AUTHENTICATED_INTERNAL_WITHIN_ORDINARY_INCHECKAD_PERMISSION_SCOPE",
    answerPolicy: "DENIED",
    requiredContext: "NONE",
    canonicalFact: "Ingen canonical verifierad state machine `BESTÄLLD → BEKRÄFTAD → PÅ VÄG` eller `ORDER SKICKAD → ... → ANKOMMEN` är etablerad.",
    canonicalHelpText: "**Ingen publicerbar processhjälp.** Vid fråga ska AI hänvisa till `KR-ORDER-001` och begränsa svaret.",
    prohibitedClaims: "Presentera någon sådan state machine som verksamhetssanning eller rekommenderad canonical process.",
  },
  {
    knowledgeId: "KR-HIST-604-PRE",
    topicModule: "Garage → AVVECKLA revision före #604",
    sourceOwner: "HISTORICAL AUDIT",
    sourcePrecedence: "P4_HISTORICAL_ONLY",
    authorityReference: "SOURCE:file_00000000c37c820abe9352ed0b23ab0d:date=2026-09-09:pre-PR604-audit",
    sourceReference: "SOURCE:file_00000000c37c820abe9352ed0b23ab0d:date=2026-09-09:pre-PR604-audit",
    validFrom: "2026-09-09",
    validTo: "2026-09-09",
    status: "SUPERSEDED",
    supersedes: "NONE",
    supersededBy: "KR-AVV-001",
    audienceRole: "AI_NONE",
    answerPolicy: "DENIED",
    requiredContext: "NONE",
    canonicalFact: "Historisk pre-#604-revision. Gap A/B/C ersattes av #604.",
    canonicalHelpText: "**Ingen current user-help får genereras från posten.**",
    prohibitedClaims: "Presentera de tre gamla gapen som aktuella Production-problem.",
  },
] as const satisfies readonly HelpbotRegistryItem[];

export type KnowledgeId = (typeof KNOWLEDGE_REGISTRY_V1)[number]['knowledgeId'];

export const KNOWLEDGE_REGISTRY_V1_ID_SET = KNOWLEDGE_REGISTRY_V1.map((item) => item.knowledgeId) as readonly KnowledgeId[];

export function registryItemById(knowledgeId: string): HelpbotRegistryItem | undefined {
  return KNOWLEDGE_REGISTRY_V1.find((item) => item.knowledgeId === knowledgeId);
}
