export const EMAIL_WHITELIST = new Set<string>([
  'per.andersson@mabi.se',
  'per.enskede@gmail.com',
  'ingemar.carqueija@mabi.se',
  'latif.mutlu@mabi.se',
  'hugo.carqueija@gmail.com',
  'benjamin.mutlu@outlook.com',
  'oliwer.fredriksson@mabi.se',
  'louise.espe@mabi.se',
  'lucas.nemeth@mabi.se',
  'isak.brandeby@mabi.se',
  'noorullah.mohammad.zarif@mabi.se',
  'maciej.krupa@mabi.se',
  'nimet.mecaj@mabi.se',
  'lukas.svensson@mabi.se',
  'leo.hedenberg@mabi.se',
  'anders.larsson@mabi.se',
  'haris.poricanin@mabi.se',
  'mikael.gronqvist@mabi.se',
  'ludvig.johansson@mabi.se',
  'joachim.mellden@mabi.se',
  'felicia.sarlov@mabi.se',
  'mohamed.ismael@mabi.se',
  'linus.croon@mabi.se',
  'wanda.andersson@mabi.se',
  'dan.hermodsson@mabi.se',
  'elvir.poricanin@mabi.se',
  'asa.andersson@mabi.se',
  'dilot_85@hotmail.com',
  'alicia.carqueija@mabi.se',
  'isak.andersson@mabi.se',
  'isakeandersson@gmail.com',
  'lucianoinzunza71@gmail.com',
  'helsingborg@mabi.se',
]);

export function isWhitelistedEmail(email: string | null | undefined): boolean {
  return !!email && EMAIL_WHITELIST.has(email.toLowerCase());
}
