/**
 * Auto-generated damage options
 * 
 * Generated from: docs/Skadetyp, Placering, Position_20251023.csv
 * Generated at: 2025-10-24T07:25:43.900Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate:damage-options
 */

export const DAMAGE_OPTIONS: Record<string, Record<string, string[]>> = {
  "Buckla": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Däck": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Motorhuv": [],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tak": [],
    "Tröskel": [
      "Höger",
      "Vänster"
    ]
  },
  "Däckskada": {
    "Däck": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ]
  },
  "Däckskada sommarhjul": {
    "Däck": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ]
  },
  "Däckskada vinterhjul": {
    "Däck": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ]
  },
  "Feltankning": {},
  "Fälgskada sommarhjul": {
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ]
  },
  "Fälgskada vinterhjul": {
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ]
  },
  "Höjdledsskada": {},
  "Intryck": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Front läpp": [
      "Höger",
      "Mitten",
      "Vänster"
    ],
    "Grill": []
  },
  "Invändig skada": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Panel (transportbil)": [],
    "Tak": []
  },
  "Jack": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Front läpp": [
      "Höger",
      "Mitten",
      "Vänster"
    ],
    "Motorhuv": [
      "Utsida"
    ],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tröskel": [
      "Höger",
      "Vänster"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Krockskada": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Front läpp": [
      "Höger",
      "Mitten",
      "Vänster"
    ],
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Glas": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Motorhuv": [
      "Utsida"
    ],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tröskel": [
      "Höger",
      "Vänster"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Krossad ruta": {
    "Bakruta": [],
    "Höger annan": [],
    "Höger bak": [],
    "Höger fram": [],
    "Tak": [],
    "Vindruta": [],
    "Vänster annan": [],
    "Vänster bak": [],
    "Vänster fram": []
  },
  "Oaktsamhet": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Däck": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Front läpp": [
      "Höger",
      "Mitten",
      "Vänster"
    ],
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Glas": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Motorhuv": [
      "Utsida"
    ],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tak": [],
    "Tröskel": [
      "Höger",
      "Vänster"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Punktering": {
    "Däck": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ]
  },
  "Repa": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Front läpp": [
      "Höger",
      "Mitten",
      "Vänster"
    ],
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Glas": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Motorhuv": [
      "Utsida"
    ],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tak": [],
    "Tröskel": [
      "Höger",
      "Vänster"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Repor": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Front läpp": [
      "Höger",
      "Mitten",
      "Vänster"
    ],
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Glas": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Motorhuv": [
      "Utsida"
    ],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tak": [],
    "Tröskel": [
      "Höger",
      "Vänster"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Skrapad": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Front läpp": [
      "Höger",
      "Mitten",
      "Vänster"
    ],
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Glas": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Motorhuv": [
      "Utsida"
    ],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tak": [],
    "Tröskel": [
      "Höger",
      "Vänster"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Skrapad fälg": {
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ]
  },
  "Spricka": {
    "Glas": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Stenskott": {
    "Annan del": [],
    "Glas": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Motorhuv": [],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tröskel": [
      "Höger",
      "Vänster"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Trasig": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  },
  "Övrigt": {
    "Annan del": [],
    "Bagagelucka": [
      "Insida",
      "Utsida"
    ],
    "Däck": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr insida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Dörr utsida": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Front läpp": [
      "Höger",
      "Mitten",
      "Vänster"
    ],
    "Fälg": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Glas": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Grill": [],
    "Motorhuv": [
      "Utsida"
    ],
    "Skärm": [
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Stötfångare fram": [
      "Bak",
      "Fram",
      "Höger bak",
      "Höger fram",
      "Vänster bak",
      "Vänster fram"
    ],
    "Tak": [],
    "Tröskel": [
      "Höger",
      "Vänster"
    ],
    "Yttre backspegel": [
      "Höger",
      "Vänster"
    ]
  }
};
